title: Github
author: deewhy381
email: deewhy381@github.com
description: > # this means to ignore newlines until "baseurl:"
  Be in the know about Github.
# social links
deewhy381: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
deewhy381:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
